# Generated by Django 5.1.3 on 2024-11-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0003_categorie_examen_ranking_color_eleve_examenresultat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='volee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='ladder.volee'),
        ),
    ]
