# Generated by Django 5.1.3 on 2024-11-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0005_eleve_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='sous_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='ladder.souscategorie'),
        ),
        migrations.AlterField(
            model_name='examenresultat',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examen_resultats', to='ladder.eleve'),
        ),
        migrations.AlterField(
            model_name='examenresultat',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examen_resultats', to='ladder.examen'),
        ),
        migrations.AlterField(
            model_name='souscategorie',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='ladder.categorie'),
        ),
    ]
