# Generated by Django 5.1.3 on 2024-12-01 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0006_alter_examen_sous_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenDifficulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('elo', models.IntegerField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='examen_difficulte/')),
            ],
        ),
        migrations.RemoveField(
            model_name='examen',
            name='date_rendu',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='elo_max',
        ),
        migrations.AddField(
            model_name='examen',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='version',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='sous_categorie/'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='ladder.souscategorie'),
        ),
        migrations.AddField(
            model_name='examen',
            name='diffculte',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='ladder.examendifficulte'),
        ),
    ]
