# Generated by Django 5.1.3 on 2024-12-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0007_examendifficulte_remove_examen_date_rendu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='diffculte',
            new_name='difficulte',
        ),
    ]
