# Generated by Django 5.1.3 on 2024-12-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0008_rename_diffculte_examen_difficulte'),
    ]

    operations = [
        migrations.AddField(
            model_name='examendifficulte',
            name='color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
