# Generated by Django 5.1.3 on 2024-12-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0009_examendifficulte_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='pseudo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
