# Generated by Django 5.1.3 on 2024-12-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0010_eleve_pseudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='version',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='label',
        ),
        migrations.AddField(
            model_name='examen',
            name='dt_debut',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='dt_fin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='fichier',
            field=models.FileField(blank=True, default=None, null=True, upload_to='examen/'),
        ),
        migrations.AddField(
            model_name='examen',
            name='texte',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='examen',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
