# Generated by Django 5.1.3 on 2024-12-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0011_rename_version_examen_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='pushup',
            field=models.IntegerField(default=0),
        ),
    ]
